version: "3"

networks:
  db-network:
    driver: bridge

services:
  db:
    image: postgres:14
    container_name: db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    networks:
      - db-network

  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    image: teachercan
    ports:
      - 8000:8000
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      # - ./db.sqlite3:/app/db.sqlite3
      - ./config:/app/config
      - ./teachercan:/app/teachercan
    command: python manage.py runserver 0.0.0.0:8000
    networks:
      - db-network

volumes:
  postgres_data: