version: "3"

networks:
  nginx-network:
    driver: bridge
  db-network:
    driver: bridge

services:
  db:
    image: postgres:14
    container_name: db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    networks:
      - nginx-network

  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    image: teachercan
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      # - ./db.sqlite3:/app/db.sqlite3
      - ./config:/app/config
      - ./teachercan:/app/teachercan
    command: gunicorn config.wsgi -w 3 -b 0.0.0.0:8000
    networks:
      - nginx-network
      - db-network
      
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - app
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      # - static:/code/static
    networks:
      - nginx-network

volumes:
  postgres_data: