# Generated by Django 5.0.2 on 2024-04-14 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('is_main', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('has_allergy', models.BooleanField(default=False)),
                ('description', models.CharField(max_length=200, null=True)),
                ('total_student_num', models.IntegerField()),
            ],
            options={
                'db_table': 'student_list',
            },
        ),
    ]
