# Generated by Django 5.0.2 on 2024-04-15 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student_lists", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentlist",
            name="total_student_num",
            field=models.IntegerField(null=True),
        ),
    ]
