# Generated by Django 5.0.2 on 2024-04-14 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('columns', '0001_initial'),
        ('student_lists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='column',
            name='student_list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='student_lists.studentlist'),
        ),
    ]
